#ifndef POMEGRANATEENGINE_ENUMERATIONS_H
#define POMEGRANATEENGINE_ENUMERATIONS_H
#include <vulkan/vulkan.h>

enum RenderMode {
    RENDER_MODE_FILL = VK_POLYGON_MODE_FILL,
    RENDER_MODE_LINE = VK_POLYGON_MODE_LINE,
    RENDER_MODE_POINT = VK_POLYGON_MODE_POINT
};

enum CullMode {
    CULL_MODE_NONE = VK_CULL_MODE_NONE,
    CULL_MODE_FRONT = VK_CULL_MODE_FRONT_BIT,
    CULL_MODE_BACK = VK_CULL_MODE_BACK_BIT,
    CULL_MODE_BOTH = VK_CULL_MODE_FRONT_AND_BACK
};

struct RenderInfo {
    RenderMode renderMode = RENDER_MODE_FILL;
    CullMode cullMode = CULL_MODE_BACK;
};

#endif //POMEGRANATEENGINE_ENUMERATIONS_H
