#ifndef POMEGRANATE_ENGINE_GRAPHICS_VULKAN_GRAPHICS_H
#define POMEGRANATE_ENGINE_GRAPHICS_VULKAN_GRAPHICS_H

#include "core.h"
#include "window.h"

#endif //POMEGRANATE_ENGINE_GRAPHICS_VULKAN_GRAPHICS_H
