#ifndef POMEGRANATEENGINE_INPUT_ENUMERATIONS_H
#define POMEGRANATEENGINE_INPUT_ENUMERATIONS_H

#include <graphics/opengl/window.h>
#include <variant>

enum ButtonState {
    BUTTON_IDLE,
    BUTTON_HELD,
    BUTTON_RELEASED,
    BUTTON_PRESSED,
};

enum GamepadID {
    GAMEPAD_1,
    GAMEPAD_2,
    GAMEPAD_3,
    GAMEPAD_4,
    GAMEPAD_5,
    GAMEPAD_6,
    GAMEPAD_7,
    GAMEPAD_8,
    GAMEPAD_9,
    GAMEPAD_10,
    GAMEPAD_11,
    GAMEPAD_12,
    GAMEPAD_13,
    GAMEPAD_14,
    GAMEPAD_15,
    GAMEPAD_16,
    GAMEPAD_ANY
};

#endif //POMEGRANATEENGINE_INPUT_ENUMERATIONS_H
