#ifndef POMEGRANATEENGINE_ENUMERATIONS_H
#define POMEGRANATEENGINE_ENUMERATIONS_H
#include <glad/glad.h>
#include <GLFW/glfw3.h>

enum RenderMode {
    RENDER_MODE_FILL = GL_FILL,
    RENDER_MODE_WIRE_FRAME = GL_LINE,
    RENDER_MODE_POINTS = GL_POINT
};

enum CullMode {
    CULL_MODE_NONE = GL_NONE,
    CULL_MODE_FRONT = GL_FRONT,
    CULL_MODE_BACK = GL_BACK,
    CULL_MODE_BOTH = GL_FRONT_AND_BACK
};

enum DepthMode {
    DEPTH_MODE_NEVER = GL_NEVER,
    DEPTH_MODE_LESS = GL_LESS,
    DEPTH_MODE_EQUAL = GL_EQUAL,
    DEPTH_MODE_LEQUAL = GL_LEQUAL,
    DEPTH_MODE_GREATER = GL_GREATER,
    DEPTH_MODE_NOTEQUAL = GL_NOTEQUAL,
    DEPTH_MODE_GEQUAL = GL_GEQUAL,
    DEPTH_MODE_ALWAYS = GL_ALWAYS
};

enum TopologyMode {
    TOPOLOGY_MODE_TRIANGLE_INDEXED = GL_TRIANGLES,
    TOPOLOGY_MODE_TRIANGLE_STRIP = GL_TRIANGLE_STRIP,
    TOPOLOGY_MODE_TRIANGLE_FAN = GL_TRIANGLE_FAN,
    TOPOLOGY_MODE_LINE_INDEXED = GL_LINES,
    TOPOLOGY_MODE_LINE_STRIP = GL_LINE_STRIP,
    TOPOLOGY_MODE_POINT = GL_POINTS
};

enum BufferType {
    BUFFER_TYPE_NONE = 0,
    BUFFER_TYPE_VERTEX = GL_ARRAY_BUFFER,
    BUFFER_TYPE_INDEX = GL_ELEMENT_ARRAY_BUFFER
};

enum InputRate {
    INPUT_RATE_VERTEX = GL_VERTEX_ATTRIB_ARRAY_POINTER,
    INPUT_RATE_INSTANCE = GL_VERTEX_ATTRIB_ARRAY_DIVISOR
};

struct RenderInfo {
    RenderMode renderMode = RENDER_MODE_FILL;
    CullMode cullMode = CULL_MODE_BACK;
    TopologyMode topologyMode = TOPOLOGY_MODE_TRIANGLE_INDEXED;
    DepthMode depthMode = DEPTH_MODE_LESS;
};

enum AttributeFormat {
    ATTRIBUTE_FORMAT_FLOAT,
    ATTRIBUTE_FORMAT_FLOAT2,
    ATTRIBUTE_FORMAT_FLOAT3,
    ATTRIBUTE_FORMAT_FLOAT4,
    ATTRIBUTE_FORMAT_INT,
    ATTRIBUTE_FORMAT_INT2,
    ATTRIBUTE_FORMAT_INT3,
    ATTRIBUTE_FORMAT_INT4,
    ATTRIBUTE_FORMAT_UNSIGNED_INT,
    ATTRIBUTE_FORMAT_UNSIGNED_INT2,
    ATTRIBUTE_FORMAT_UNSIGNED_INT3,
    ATTRIBUTE_FORMAT_UNSIGNED_INT4
};

enum AttributeType {
    ATTRIBUTE_TYPE_POSITION,
    ATTRIBUTE_TYPE_NORMAL,
    ATTRIBUTE_TYPE_TANGENT,
    ATTRIBUTE_TYPE_BITANGENT,
    ATTRIBUTE_TYPE_TEXCOORD,
    ATTRIBUTE_TYPE_COLOR,
    ATTRIBUTE_TYPE_BONE_ID,
    ATTRIBUTE_TYPE_BONE_WEIGHT,
    ATTRIBUTE_TYPE_CUSTOM
};

struct VertexBindingInfo {
    uint32_t binding;
    uint32_t stride;
    uint32_t offset;
    InputRate inputRate;
};

struct VertexAttributeInfo {
    uint32_t binding;
    uint32_t location;
    size_t offset;
    AttributeFormat format;
    AttributeType type;
};

#endif //POMEGRANATEENGINE_ENUMERATIONS_H
